# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.image_dir: '%kernel.project_dir%/var/storage/images'
    app.image_cache_dir: '%kernel.project_dir%/var/storage/cache'
    default_base_url: "http://127.0.0.1"
    router.request_context.base_url: "%env(default:default_base_url:SYMFONY_DEFAULT_ROUTE_URL)%"
    mailer.from_email: '%env(MAILER_FROM_EMAIL)%'
    mailer.admin_email: '%env(MAILER_ADMIN_EMAIL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $secret: '%kernel.secret%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    League\Glide\Server:
        factory: ['League\Glide\ServerFactory', create]
        arguments:
          - source: '%app.image_dir%'
            cache: '%app.image_cache_dir%'